### ISSUE TITLE
[master] Project Plan

### ISSUE THREAD

**Issue by nikolaswise** [nikolaswise/lower-albina#1]
# Lower Albina Map

Project Plan: Nikolas Wise
## Introduction

From a design perspective, contemporary tools for creating maps on the internet are restrictive. The current approach to cartographic maps more paint-by-numbers than informed by design decisions. Our Esri-style approach to out of the box data rendering over pre-baked basemaps is convenient to data analysts, but more or less fails for purposes that do not align or accept the base assumptions we make. Likewise, the Mapbox approach to 'designing' maps boils down to picking finishes.

We've been developing tools for more intensive cartography for web maps - Esri Leaflet bridges the gap between our powerful data and analytics and open source mapping tools; along with thing like Angular.js structures for smoother mapping work flows. Ideally, we will be able to arrive at an environment that lowers the technological barriers that stand between designers and cartographers and creative applications of web maps.

The Lower Albina project is an attempt to create such an environment - and a resultant map that accomplishes goals that current webmap systems are not.
## Questions
1. **How can the medium of the web map, though visual and interactive design, create a meaningful reflection of the Lower Albina industrial districts sense of place?**
   - How can the specific qualities of the webmap facilitate the communication of specific cultural qualities associated with a place and the inhabitants of that place?
   - What is a meaningful way to incorporate marginalia, diagrams, and explanatory legends and texts in a webmap?
   - The previous media of maps had their inherent properties and solutions - how can we we learn from these design lessons and explore our own?
   - As the means of production for webmaps are common across a wide swath of web content and objects, how can we package diverse designed experiences together in a seamless - or intentionally seamed - manner?
   - How can a webmap with no pre-selected content or design elements question the implicit assumptions that institutional designs make, or undermine and highlight the inherent political power associated with map making?
2. **How can we create mapping tools and environments that make accomplishing this more accessible?**
## Goals

Esrigoalâ„¢: Create a development environment and set of tools that allow for richer design process that currently available for web cartography.

NKgoalâ„¢: Create a compelling design object exploring the cultural sense of place within the Lower Albina commercial district.
## Setup Steps
- [x] Create project checklist.
- [x] Critical design analysis of effective print maps, including 1940's Swiss Topographic maps and historical Norwegian maps.
- [ ] Identify theoretical strengths and weakness with screen-as-media
- [ ] Identify authoritative assumptions in current webmap structures
- [ ] List physical geographic qualities and peculiarities that work towards Lower Albina's sense of place.
- [ ] Identify extant design tools, problems that require new design tools, and formulate plan for creating these tools,
## Development Steps
- [ ] Collect, collate, and analyze data from Lower Albina
- [ ] Collect and create narrative, visual, and anecdotal form of non-geographic assets that reflect cultural sense of place
- [ ] Create structures and design tools
- [ ] Incorporate non-graphic assets, legends, and marginalia
- [ ] Test, revise, and repeat use of tools.
## Final Steps
- [ ] Produce final design object as a stand-alone and coherent project.
- [ ] Document and share structures, tools, and development environments
## Timeline

To be determined.

**Comment by nikolaswise** [comment]
# Map as Context

A critical design analysis of paper classical paper maps, focusing on examples from historical Norwegian geographic maps 1770–1940.

## Introduction - Mapping as visual design tool

![img/01_1887.jpg](https://cloud.githubusercontent.com/assets/1987772/4670754/c94b6170-5579-11e4-8e9a-673295c3487c.jpg)

'The Map' is a fairly general conceptual model, a term  valid for describing a wide range of objects. The map at it's core is a tool to provide context for the specific, and illuminate the general. A good map is tailored to communicate on both of these scales simultaneously. They exist to solve a specific problem, defined and shaped by the broader culture that has the problem. In this way the map-as-object inherently takes a perspective inseparable from the societal culture that creates and uses the object. As a tool of communication, an analysis of the formal aspects with a knowledge of broader context can illuminate specific decisions, needs, and solutions that can provide the design tools needed to create maps on the web as successful, and beautiful, as maps on paper.

## Means of production

![img/02_1720.jpg](https://cloud.githubusercontent.com/assets/1987772/4670802/20a9ed56-557a-11e4-8361-aeff9b20f4ef.jpg)

Before the advent of digital production and distribution, there were only two types of maps - one-off, non-reproducible maps (drawing as object), and multiple, reproducible maps (print as object). In this way, the technical history of the map is tied directly with the history of printmaking. While the drawing of the map is requisite for both objects, the printed map added a technical process to the creation of maps, influencing the style of requirements for for the drawn map. As with the addition of digital technical processes today, the underlying drawing and visual tools needed to succeed within each the new environments of technical production change with production techniques.

![img/03_1940.jpg](https://cloud.githubusercontent.com/assets/1987772/4670833/61b34b62-557a-11e4-9a8d-f5355b76b81c.jpg)

The maps from Norway that were produced in the 1920's through 50's were printed lithographically, most likely using an offset press. Earlier maps from the 1890's are also lithographic, although these are likely printed on traditional stone lithography presses. The lithographic process is binary - either inked or not inked - rather than truly tonal, so this leads to the need to create tonal range via cross-hatching and half-toning. As with any printing process, each color was drawn as a single plate - or layer - meaning that a limited color palette is rewarded by lowered production costs. In this way, it's very common to see two or three color maps using a wide range of halftones to create depth and richness, along with the use of thematically grouping objects by color. Landscape features occupy the key (black) layer, communication of water features shares the blue layer, building footprints are gathered all together on the orange layer. This visual technique keeps a single set of data together on a single drawn layer, with the design advantage of having clear, semantic, color-coded maps.

## Formal aspects

Thinking of 'map-as-object' leads us to consider the map as the _entire_ object. Rather than conceptually separating the map from the frame from the margin from the scale bar and legend, the map needs to be thought of as the entire physical object of the paper and the print. These concepts are inextricable, and their consideration leads to the design solutions we see today. The printing plate has physical limitations of workable size, the paper has the physical limitations of production and quality, the ink has the physical limitations of light-fastness, pigment density, and transparency.

![img/04_1920.jpg](https://cloud.githubusercontent.com/assets/1987772/4670899/28807e0e-557b-11e4-88b5-0e5fb9decf5e.jpg)

We see the response to these physical limitations in the layout and design of the printed image: The paper can be larger than the plate giving room for whitespace that frames the printed area, allowing the hands hold the object without obscuring it and creating a focal point in the interplay between figure/ground. Visual framing devices - representations of frames, double ruled ornaments - clearly mark the transition from margin to image. This creates room for the framing device to pull double duty as decorative assistance to the image and semantic indicators of scale, proportion, and contextual reference.

![img/05_18901940.jpg](https://cloud.githubusercontent.com/assets/1987772/4670943/a0bc87d2-557b-11e4-977a-8781e6baae92.jpg)

The plates for the multi-layered geographic representation may be separated from the legends, scales, and other marginalia. This means that the legend - without which the map must rely on implied semantic connotations - and scale bar - without which the map looses it's reference to the lived-in world - can occupy the white space, either centered along on axis, or across the compass points.

![img/07_1844.jpg](https://cloud.githubusercontent.com/assets/1987772/4671011/7771b5a4-557c-11e4-8e42-7612e28e864f.jpg)
![img/06_1934.jpg](https://cloud.githubusercontent.com/assets/1987772/4670992/47530346-557c-11e4-9489-391840bcaa9a.jpg)

The map-as-object of multi-layered printed images on paper invites these specific solutions to a set of questions: How do we distribute this image? How do we make sense of it once we have? How do I understand the cultural context of this object? In these illustrations - digital representations of physical objects - we naturally avoid another aspect of the map-as-object: the reverse side of the sheet. The contents of both the recto and verso, along with the physical context of it's distribution (bound in an atlas? rolled and sealed? sheafed flat in a stack and stored?) will provide further understanding of the map.

## Exaggeration, simplification, and generalization

![img/08_1901.jpg](https://cloud.githubusercontent.com/assets/1987772/4671023/a6e7f7e4-557c-11e4-934e-2d6aa4057ce8.jpg)

It could be argued that any exercise in mapping is the practice of exaggeration, simplification, and generalization. Representing the complexity of the lived world to semiotic structures of the map through design requires all three techniques of reduction, filtered through the subject of communication. Accepting that the tools available for graphic communication will necessarily distort or obscure the reality of the place being mapped, the question becomes how to use this distortion to strengthen the ideas being presented.

![img/09_1775.jpg](https://cloud.githubusercontent.com/assets/1987772/4671042/c9cdc4e6-557c-11e4-82b7-cdffb821ce0e.jpg)

**Exaggeration**
The depiction of the rolling hills from the historical Norwegian maps of the 1770's show graphic exaggeration of the landscape in order to communicate the density and character of the countryside, not necessarily the precise contours of the landscape, but rather the nature of the topography – perhaps highlighting the valleys and ravines _between_ the hills rather than the hills themselves. This technique is seen with the early, hand drawn maps, and is carried through for several decades.

![img/10_1890.jpg](https://cloud.githubusercontent.com/assets/1987772/4671055/ff8c8824-557c-11e4-92bf-b32540895071.jpg)
![img/11_1890.jpg](https://cloud.githubusercontent.com/assets/1987772/4671070/23257ff2-557d-11e4-937d-54e37568f8b2.jpg)

**Simplification**
The removal of as many graphic elements as possible to leave behind only the essential, meaningful information forces the designer to ask what they are trying to communicate, and what they absolutely need to include to provide meaningful context. The question becomes what can be removed from a map, what can be abandoned without harming the intended message. Seen at the extreme, this technique can be used to provide a simple, clear map on a single topic.

![img/12_1805.jpg](https://cloud.githubusercontent.com/assets/1987772/4671087/504b3440-557d-11e4-925a-8fbd0d139c9b.jpg)

**Generalization**
While symbology is the most common form of generalization with the map – this dot represents this structure, defined by the legend – there are some strong examples of generalization of both built and natural forms throughout the entire collection of historical Norwegian maps. Leaving behind the precise symbols, the idea and feeling of a place can be communicated by the generalized shapes of things, their interplay and juxtaposition in their simplicity can evoke a deeper knowledge of place than the precise representation. In this section for an 1805 map, the uneven shapes of what seem to be fields jostle with the simple drawings of trees, the hills, the rivers, and the yellow demarcation lines. The abstraction of the terrain makes it more of a place one that can be imagined and recognized.
